name: Notify Discord on Release
on:
  release:
    types: [published]

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Notes
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          # Use jq to format the release body cleanly into JSON text
          PAYLOAD=$(jq -n --arg content "$RELEASE_BODY" '{content: $content}')
          
          # Send the raw description to Discord
          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" "$DISCORD_WEBHOOK"
